apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress
  name: ingress-service
  namespace: front-end
spec:
  ports:
  - name: ingress-ports
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ingress
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress
  name: ingress-deployment
  namespace: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingress
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
