apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
  name: front-end-service
  namespace: front-end
spec:
  ports:
  - name: front-end-ports
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: front-end
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: front-end-deployment
  namespace: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30